-- RedDefinesProjects
-- Must be loaded AFTER RedDefinesUnits
-- Author: Gedemon
-- DateCreated: 5/6/2012 8:40:08 PM
--------------------------------------------------------------


-- Projects Type ID

-- FR
PROJECT_H39				= GameInfo.Projects.PROJECT_TANK_H39.ID
PROJECT_R40				= GameInfo.Projects.PROJECT_TANK_R40.ID
PROJECT_ARL_44			= GameInfo.Projects.PROJECT_TANK_ARL44.ID
PROJECT_W15_TCC			= GameInfo.Projects.PROJECT_TANK_DESTROYER_W15_TCC.ID
PROJECT_AMR35_ZT3		= GameInfo.Projects.PROJECT_TANK_DESTROYER_AMR35_ZT3.ID
PROJECT_37L				= GameInfo.Projects.PROJECT_TANK_DESTROYER_37L.ID
PROJECT_SAU40			= GameInfo.Projects.PROJECT_ASSAULT_GUN_SAU40.ID
PROJECT_HOTCHKISS		= GameInfo.Projects.PROJECT_MOBILE_AA_GUN_HOTCHKISS.ID
PROJECT_MB152			= GameInfo.Projects.PROJECT_FIGHTER_MB152.ID
PROJECT_D520			= GameInfo.Projects.PROJECT_FIGHTER_D520.ID
PROJECT_LN401			= GameInfo.Projects.PROJECT_BOMBER_LN401.ID
PROJECT_BR690			= GameInfo.Projects.PROJECT_BOMBER_BR690.ID
PROJECT_JOFFRE			= GameInfo.Projects.PROJECT_CARRIER_JOFFRE.ID

-- RU
PROJECT_BT7				= GameInfo.Projects.PROJECT_TANK_BT7.ID
PROJECT_T70				= GameInfo.Projects.PROJECT_TANK_T70.ID
PROJECT_T34				= GameInfo.Projects.PROJECT_TANK_T34.ID
PROJECT_T34_76			= GameInfo.Projects.PROJECT_TANK_T34_76.ID
PROJECT_T34_85			= GameInfo.Projects.PROJECT_TANK_T34_85.ID
PROJECT_KV1				= GameInfo.Projects.PROJECT_TANK_KV1.ID
PROJECT_IS_1			= GameInfo.Projects.PROJECT_TANK_IS_1.ID
PROJECT_IS_2			= GameInfo.Projects.PROJECT_TANK_IS_2.ID
PROJECT_IS_3			= GameInfo.Projects.PROJECT_TANK_IS_3.ID
PROJECT_IS_7			= GameInfo.Projects.PROJECT_TANK_IS_7.ID
PROJECT_SU122			= GameInfo.Projects.PROJECT_ASSAULT_GUN_SU122.ID
PROJECT_SU152			= GameInfo.Projects.PROJECT_ASSAULT_GUN_SU152.ID
PROJECT_KV2				= GameInfo.Projects.PROJECT_ASSAULT_GUN_KV2.ID
PROJECT_ISU122			= GameInfo.Projects.PROJECT_ASSAULT_GUN_ISU122.ID
PROJECT_ISU152			= GameInfo.Projects.PROJECT_ASSAULT_GUN_ISU152.ID
PROJECT_ZIS30			= GameInfo.Projects.PROJECT_TANK_DESTROYER_ZIS30.ID
PROJECT_SU76			= GameInfo.Projects.PROJECT_TANK_DESTROYER_SU76.ID
PROJECT_SU85			= GameInfo.Projects.PROJECT_TANK_DESTROYER_SU85.ID
PROJECT_SU100			= GameInfo.Projects.PROJECT_TANK_DESTROYER_SU100.ID
PROJECT_SU26			= GameInfo.Projects.PROJECT_MOBILE_ARTILLERY_SU26.ID
PROJECT_ZSU37			= GameInfo.Projects.PROJECT_MOBILE_AA_GUN_ZSU37.ID
PROJECT_BM13			= GameInfo.Projects.PROJECT_MOBILE_ARTILLERY_BM13.ID
PROJECT_BM13_16			= GameInfo.Projects.PROJECT_MOBILE_ARTILLERY_BM13_16.ID
PROJECT_LAGG3			= GameInfo.Projects.PROJECT_FIGHTER_LAGG3.ID
PROJECT_LA5				= GameInfo.Projects.PROJECT_FIGHTER_LA5.ID
PROJECT_LA5_V2			= GameInfo.Projects.PROJECT_FIGHTER_LA5_V2.ID
PROJECT_LA7				= GameInfo.Projects.PROJECT_FIGHTER_LA7.ID
PROJECT_YAK7			= GameInfo.Projects.PROJECT_FIGHTER_YAK7.ID
PROJECT_YAK9			= GameInfo.Projects.PROJECT_FIGHTER_YAK9.ID
PROJECT_IL2				= GameInfo.Projects.PROJECT_BOMBER_IL2.ID
PROJECT_IL2M3			= GameInfo.Projects.PROJECT_BOMBER_IL2M3.ID
PROJECT_IL10			= GameInfo.Projects.PROJECT_BOMBER_IL10.ID
PROJECT_PE8				= GameInfo.Projects.PROJECT_BOMBER_PE8.ID
PROJECT_TU2				= GameInfo.Projects.PROJECT_BOMBER_TU2.ID
PROJECT_IL4				= GameInfo.Projects.PROJECT_BOMBER_IL4.ID
PROJECT_SOYUZ			= GameInfo.Projects.PROJECT_BATTLESHIP_SOYUZ.ID

-- GE
PROJECT_PANZER_II_L		= GameInfo.Projects.PROJECT_TANK_PANZER_II_L.ID
PROJECT_PANZER_III		= GameInfo.Projects.PROJECT_TANK_PANZER_III.ID
PROJECT_PANZER_III_J	= GameInfo.Projects.PROJECT_TANK_PANZER_III_J.ID
PROJECT_PANZER_IV		= GameInfo.Projects.PROJECT_TANK_PANZER_IV.ID
PROJECT_PANZER_IV_G		= GameInfo.Projects.PROJECT_TANK_PANZER_IV_G.ID
PROJECT_PANZER_IV_H		= GameInfo.Projects.PROJECT_TANK_PANZER_IV_H.ID
PROJECT_PANZER_V		= GameInfo.Projects.PROJECT_TANK_PANZER_V_PANTHER.ID
PROJECT_PANZER_VI		= GameInfo.Projects.PROJECT_TANK_PANZER_VI_TIGER.ID
PROJECT_PANZER_VIB		= GameInfo.Projects.PROJECT_TANK_PANZER_VIB_TIGER_II.ID
PROJECT_PANZER_VIII		= GameInfo.Projects.PROJECT_TANK_PANZER_VIII_MAUS.ID
PROJECT_STUG_III		= GameInfo.Projects.PROJECT_ASSAULT_GUN_STUG_III.ID
PROJECT_STUG_III_F		= GameInfo.Projects.PROJECT_ASSAULT_GUN_STUG_III_F.ID
PROJECT_STUG_III_G		= GameInfo.Projects.PROJECT_ASSAULT_GUN_STUG_III_G.ID
PROJECT_STUG_IV			= GameInfo.Projects.PROJECT_ASSAULT_GUN_STUG_IV.ID
PROJECT_BRUMMBAR		= GameInfo.Projects.PROJECT_ASSAULT_GUN_BRUMMBAR.ID
PROJECT_STURMTIGER		= GameInfo.Projects.PROJECT_ASSAULT_GUN_STURMTIGER.ID
PROJECT_MARDER_II		= GameInfo.Projects.PROJECT_TANK_DESTROYER_MARDER_II.ID
PROJECT_MARDER_II_D		= GameInfo.Projects.PROJECT_TANK_DESTROYER_MARDER_II_D.ID
PROJECT_MARDER_III		= GameInfo.Projects.PROJECT_TANK_DESTROYER_MARDER_III.ID
PROJECT_MARDER_III_H	= GameInfo.Projects.PROJECT_TANK_DESTROYER_MARDER_III_H.ID
PROJECT_MARDER_III_M	= GameInfo.Projects.PROJECT_TANK_DESTROYER_MARDER_III_M.ID
PROJECT_HETZER			= GameInfo.Projects.PROJECT_TANK_DESTROYER_HETZER.ID
PROJECT_NASHORN			= GameInfo.Projects.PROJECT_TANK_DESTROYER_NASHORN.ID
PROJECT_PZJ_IV			= GameInfo.Projects.PROJECT_TANK_DESTROYER_PZJ_IV.ID
PROJECT_PZJ_IV_L70		= GameInfo.Projects.PROJECT_TANK_DESTROYER_PZJ_IV_L70.ID
PROJECT_JAGDPANTHER		= GameInfo.Projects.PROJECT_TANK_DESTROYER_JAGDPANTHER.ID
PROJECT_FERDINAND		= GameInfo.Projects.PROJECT_TANK_DESTROYER_FERDINAND.ID
PROJECT_JAGDTIGER		= GameInfo.Projects.PROJECT_TANK_DESTROYER_JAGDTIGER.ID
PROJECT_FLK_PZI			= GameInfo.Projects.PROJECT_MOBILE_AA_GUN_FLK_PZI.ID
PROJECT_FLK_PZ38		= GameInfo.Projects.PROJECT_MOBILE_AA_GUN_FLK_PZ38.ID
PROJECT_MOBELWAGEN		= GameInfo.Projects.PROJECT_MOBILE_AA_GUN_MOBELWAGEN.ID
PROJECT_WIRBELWIND		= GameInfo.Projects.PROJECT_MOBILE_AA_GUN_WIRBELWIND.ID
PROJECT_OSTWIND			= GameInfo.Projects.PROJECT_MOBILE_AA_GUN_OSTWIND.ID
PROJECT_KUGELBLITZ		= GameInfo.Projects.PROJECT_MOBILE_AA_GUN_KUGELBLITZ.ID
PROJECT_COELIAN			= GameInfo.Projects.PROJECT_MOBILE_AA_GUN_COELIAN.ID
PROJECT_BISON			= GameInfo.Projects.PROJECT_MOBILE_ARTILLERY_BISON.ID
PROJECT_GRILLE			= GameInfo.Projects.PROJECT_MOBILE_ARTILLERY_GRILLE.ID
PROJECT_WESPE			= GameInfo.Projects.PROJECT_MOBILE_ARTILLERY_WESPE.ID
PROJECT_HUMMEL			= GameInfo.Projects.PROJECT_MOBILE_ARTILLERY_HUMMEL.ID
PROJECT_BF109F			= GameInfo.Projects.PROJECT_FIGHTER_BF109_F.ID
PROJECT_BF109G			= GameInfo.Projects.PROJECT_FIGHTER_BF109_G.ID
PROJECT_FW190			= GameInfo.Projects.PROJECT_FIGHTER_FW190.ID
PROJECT_ME262			= GameInfo.Projects.PROJECT_FIGHTER_ME262.ID
PROJECT_BF110F4			= GameInfo.Projects.PROJECT_FIGHTER_BF110_F4.ID
PROJECT_JU88C			= GameInfo.Projects.PROJECT_FIGHTER_JU88_C.ID
PROJECT_HE219			= GameInfo.Projects.PROJECT_FIGHTER_HE219.ID
PROJECT_HE177			= GameInfo.Projects.PROJECT_BOMBER_HE177.ID
PROJECT_AR234			= GameInfo.Projects.PROJECT_BOMBER_AR234.ID
PROJECT_HO229			= GameInfo.Projects.PROJECT_BOMBER_HO229.ID
PROJECT_ZEPPELIN		= GameInfo.Projects.PROJECT_CARRIER_ZEPPELIN.ID
PROJECT_Z23				= GameInfo.Projects.PROJECT_DESTROYER_TYPE_1936A.ID
PROJECT_U_BOAT2			= GameInfo.Projects.PROJECT_SUBMARINE_U_BOAT2.ID

-- UK
PROJECT_M3GRANT			= GameInfo.Projects.PROJECT_TANK_M3_GRANT.ID
PROJECT_TETRARCH		= GameInfo.Projects.PROJECT_TANK_TETRARCH.ID
PROJECT_MATILDAI		= GameInfo.Projects.PROJECT_TANK_MATILDA_I.ID
PROJECT_MATILDAII		= GameInfo.Projects.PROJECT_TANK_MATILDA_II.ID
PROJECT_CRUISER_II		= GameInfo.Projects.PROJECT_TANK_CRUISER_MKII.ID
PROJECT_CRUISER_III		= GameInfo.Projects.PROJECT_TANK_CRUISER_MKIII.ID
PROJECT_CRUISER_IV		= GameInfo.Projects.PROJECT_TANK_CRUISER_MKIV.ID
PROJECT_A15				= GameInfo.Projects.PROJECT_TANK_A15_CRUSADER.ID
PROJECT_A15_MKIII		= GameInfo.Projects.PROJECT_TANK_A15_CRUSADER_MKIII.ID
PROJECT_A13				= GameInfo.Projects.PROJECT_TANK_A13_MKIII.ID
PROJECT_VALENTINE		= GameInfo.Projects.PROJECT_TANK_VALENTINE.ID
PROJECT_CAVALIER		= GameInfo.Projects.PROJECT_TANK_A24_CAVALIER.ID
PROJECT_CENTAUR			= GameInfo.Projects.PROJECT_TANK_A27_CENTAUR.ID
PROJECT_CROMWELL		= GameInfo.Projects.PROJECT_TANK_CROMWELL.ID
PROJECT_CHALLENGER		= GameInfo.Projects.PROJECT_TANK_A30_CHALLENGER.ID
PROJECT_COMET			= GameInfo.Projects.PROJECT_TANK_A34_COMET.ID
PROJECT_M4_FIREFLY		= GameInfo.Projects.PROJECT_TANK_M4_FIREFLY.ID
PROJECT_CHURCHILL		= GameInfo.Projects.PROJECT_TANK_CHURCHILL.ID
PROJECT_CENTURION		= GameInfo.Projects.PROJECT_TANK_A41_CENTURION.ID
PROJECT_TORTOISE		= GameInfo.Projects.PROJECT_TANK_A39_TORTOISE.ID
PROJECT_ARCHER			= GameInfo.Projects.PROJECT_TANK_DESTROYER_ARCHER.ID
PROJECT_CRUSADER		= GameInfo.Projects.PROJECT_MOBILE_AA_GUN_CRUSADER.ID
PROJECT_PRIEST			= GameInfo.Projects.PROJECT_MOBILE_ARTILLERY_PRIEST.ID
PROJECT_BISHOP			= GameInfo.Projects.PROJECT_MOBILE_ARTILLERY_BISHOP.ID
PROJECT_SEXTON			= GameInfo.Projects.PROJECT_MOBILE_ARTILLERY_SEXTON.ID
PROJECT_HURRICANE_II	= GameInfo.Projects.PROJECT_FIGHTER_HURRICANE_MKII.ID
PROJECT_SPITFIRE_V		= GameInfo.Projects.PROJECT_FIGHTER_SPITFIRE_MKV.ID
PROJECT_SPITFIRE_IX		= GameInfo.Projects.PROJECT_FIGHTER_SPITFIRE_MKIX.ID
PROJECT_TYPHOON			= GameInfo.Projects.PROJECT_FIGHTER_TYPHOON.ID
PROJECT_TEMPEST			= GameInfo.Projects.PROJECT_FIGHTER_TEMPEST.ID
PROJECT_WHIRLWIND		= GameInfo.Projects.PROJECT_FIGHTER_WHIRLWIND.ID
PROJECT_BEAUFIGHTER		= GameInfo.Projects.PROJECT_FIGHTER_BEAUFIGHTER.ID
PROJECT_METEOR			= GameInfo.Projects.PROJECT_FIGHTER_METEOR.ID
PROJECT_MOSQUITO		= GameInfo.Projects.PROJECT_BOMBER_MOSQUITO.ID
PROJECT_LANCASTER		= GameInfo.Projects.PROJECT_BOMBER_LANCASTER.ID
PROJECT_HALIFAX			= GameInfo.Projects.PROJECT_BOMBER_HALIFAX.ID
PROJECT_ARK_ROYAL		= GameInfo.Projects.PROJECT_CARRIER_ARK_ROYAL.ID
PROJECT_ILLUSTRIOUS		= GameInfo.Projects.PROJECT_CARRIER_ILLUSTRIOUS.ID
PROJECT_U_CLASS			= GameInfo.Projects.PROJECT_SUBMARINE_UCLASS.ID


-- IT
PROJECT_L6_40			= GameInfo.Projects.PROJECT_TANK_L6_40.ID
PROJECT_M11_39			= GameInfo.Projects.PROJECT_TANK_M11_39.ID
PROJECT_M13_40			= GameInfo.Projects.PROJECT_TANK_M13_40.ID
PROJECT_M14_41			= GameInfo.Projects.PROJECT_TANK_M14_41.ID
PROJECT_M15_42			= GameInfo.Projects.PROJECT_TANK_M15_42.ID
PROJECT_P26_40			= GameInfo.Projects.PROJECT_TANK_P26_40.ID
PROJECT_SM41			= GameInfo.Projects.PROJECT_ASSAULT_GUN_M41.ID
PROJECT_L40				= GameInfo.Projects.PROJECT_TANK_DESTROYER_L40.ID
PROJECT_M41				= GameInfo.Projects.PROJECT_TANK_DESTROYER_M41.ID
PROJECT_M42M			= GameInfo.Projects.PROJECT_TANK_DESTROYER_M42M.ID
PROJECT_M42T			= GameInfo.Projects.PROJECT_TANK_DESTROYER_M42T.ID
PROJECT_M43				= GameInfo.Projects.PROJECT_TANK_DESTROYER_M43.ID
PROJECT_AUTOCANNONE		= GameInfo.Projects.PROJECT_MOBILE_AA_GUN_AUTOCANNONE.ID
PROJECT_G50				= GameInfo.Projects.PROJECT_FIGHTER_G50.ID
PROJECT_G55				= GameInfo.Projects.PROJECT_FIGHTER_G55.ID
PROJECT_CAPRONI			= GameInfo.Projects.PROJECT_FIGHTER_CAPRONI.ID
PROJECT_MC202			= GameInfo.Projects.PROJECT_FIGHTER_C202.ID
PROJECT_MC205			= GameInfo.Projects.PROJECT_FIGHTER_C205.ID
PROJECT_SM84			= GameInfo.Projects.PROJECT_BOMBER_SM84.ID
PROJECT_AQUILA			= GameInfo.Projects.PROJECT_CARRIER_AQUILA.ID

-- US
PROJECT_M3A1HT			= GameInfo.Projects.PROJECT_AMERICAN_MECH_INFANTRY.ID
PROJECT_M5STUART		= GameInfo.Projects.PROJECT_TANK_M5_STUART.ID
PROJECT_M24CHAFFEE		= GameInfo.Projects.PROJECT_TANK_M24_CHAFFEE.ID
PROJECT_M4SHERMAN		= GameInfo.Projects.PROJECT_TANK_SHERMAN.ID
PROJECT_M4A1SHERMANIIA	= GameInfo.Projects.PROJECT_TANK_SHERMAN_IIA.ID
PROJECT_SHERMAN_III		= GameInfo.Projects.PROJECT_TANK_SHERMAN_III.ID
PROJECT_SHERMANIIIA		= GameInfo.Projects.PROJECT_TANK_SHERMAN_IIIA.ID
PROJECT_SHERMAN_IV		= GameInfo.Projects.PROJECT_TANK_SHERMAN_IV.ID
PROJECT_JUMBO			= GameInfo.Projects.PROJECT_TANK_SHERMAN_JUMBO.ID
PROJECT_EASYEIGHT		= GameInfo.Projects.PROJECT_TANK_SHERMAN_EASYEIGHT.ID
PROJECT_M26 			= GameInfo.Projects.PROJECT_TANK_M26_PERSHING.ID
PROJECT_T28_95			= GameInfo.Projects.PROJECT_TANK_T28_95.ID
PROJECT_M7				= GameInfo.Projects.PROJECT_MOBILE_ARTILLERY_M7.ID
PROJECT_M12				= GameInfo.Projects.PROJECT_MOBILE_ARTILLERY_M12.ID
PROJECT_M40				= GameInfo.Projects.PROJECT_MOBILE_ARTILLERY_M40.ID
PROJECT_ACHILLES		= GameInfo.Projects.PROJECT_TANK_DESTROYER_ACHILLES.ID
PROJECT_M10				= GameInfo.Projects.PROJECT_TANK_DESTROYER_M10.ID
PROJECT_M18				= GameInfo.Projects.PROJECT_TANK_DESTROYER_M18.ID
PROJECT_M36				= GameInfo.Projects.PROJECT_TANK_DESTROYER_M36.ID
PROJECT_M16A1			= GameInfo.Projects.PROJECT_MOBILE_AA_GUN_M16A1.ID
PROJECT_P47				= GameInfo.Projects.PROJECT_FIGHTER_P47.ID
PROJECT_P38				= GameInfo.Projects.PROJECT_FIGHTER_P38.ID
PROJECT_P40				= GameInfo.Projects.PROJECT_FIGHTER_P40.ID
PROJECT_P51				= GameInfo.Projects.PROJECT_FIGHTER_P51.ID
PROJECT_F4F				= GameInfo.Projects.PROJECT_FIGHTER_F4F.ID
PROJECT_F6F				= GameInfo.Projects.PROJECT_FIGHTER_F6F.ID
PROJECT_F4U				= GameInfo.Projects.PROJECT_FIGHTER_F4U.ID
PROJECT_SB2C			= GameInfo.Projects.PROJECT_BOMBER_SB2C.ID
PROJECT_TBF				= GameInfo.Projects.PROJECT_BOMBER_TBF.ID
PROJECT_A20				= GameInfo.Projects.PROJECT_BOMBER_A20.ID
PROJECT_B24				= GameInfo.Projects.PROJECT_BOMBER_B24.ID
PROJECT_B25				= GameInfo.Projects.PROJECT_BOMBER_B25.ID
PROJECT_B29				= GameInfo.Projects.PROJECT_BOMBER_B29.ID
PROJECT_FLETCHER		= GameInfo.Projects.PROJECT_DESTROYER_FLETCHER.ID
PROJECT_IOWA			= GameInfo.Projects.PROJECT_BATTLESHIP_IOWA.ID
PROJECT_ESSEX			= GameInfo.Projects.PROJECT_CARRIER_ESSEX.ID

-- JP
PROJECT_TYPE97_SHINHOTO	= GameInfo.Projects.PROJECT_TANK_TYPE97_SHINHOTO.ID
PROJECT_TYPE1			= GameInfo.Projects.PROJECT_TANK_TYPE1_CHI_HE.ID
PROJECT_TYPE3			= GameInfo.Projects.PROJECT_TANK_TYPE3_CHI_NU.ID
PROJECT_TYPE4			= GameInfo.Projects.PROJECT_TANK_TYPE4_KE_NU.ID
PROJECT_TYPE4_CHITO		= GameInfo.Projects.PROJECT_TANK_TYPE4_CHI_TO.ID
PROJECT_TYPE5			= GameInfo.Projects.PROJECT_TANK_TYPE5_CHI_RI.ID
PROJECT_TYPE100			= GameInfo.Projects.PROJECT_TANK_TYPE100.ID
PROJECT_TYPE2			= GameInfo.Projects.PROJECT_ASSAULT_GUN_TYPE2.ID
PROJECT_HO_NI_I			= GameInfo.Projects.PROJECT_TANK_DESTROYER_HO_NI_I.ID
PROJECT_HO_NI_II		= GameInfo.Projects.PROJECT_TANK_DESTROYER_HO_NI_II.ID
PROJECT_HO_NI_III		= GameInfo.Projects.PROJECT_TANK_DESTROYER_HO_NI_III.ID
PROJECT_NA_TO			= GameInfo.Projects.PROJECT_TANK_DESTROYER_NA_TO.ID
PROJECT_HO_RO			= GameInfo.Projects.PROJECT_MOBILE_ARTILLERY_HO_RO.ID
PROJECT_HA_TO			= GameInfo.Projects.PROJECT_MOBILE_ARTILLERY_HA_TO.ID
PROJECT_TYPE98			= GameInfo.Projects.PROJECT_MOBILE_AA_GUN_TYPE98.ID
PROJECT_A6M2			= GameInfo.Projects.PROJECT_FIGHTER_A6M2_ZERO.ID
PROJECT_A6M5			= GameInfo.Projects.PROJECT_FIGHTER_A6M5_ZERO.ID
PROJECT_A7M				= GameInfo.Projects.PROJECT_FIGHTER_A7M.ID
PROJECT_KI43			= GameInfo.Projects.PROJECT_FIGHTER_KI43.ID
PROJECT_KI44			= GameInfo.Projects.PROJECT_FIGHTER_KI44.ID
PROJECT_KI84			= GameInfo.Projects.PROJECT_FIGHTER_KI84.ID
PROJECT_KI61			= GameInfo.Projects.PROJECT_FIGHTER_KI61.ID
PROJECT_KI100			= GameInfo.Projects.PROJECT_FIGHTER_KI100.ID
PROJECT_KI100_II		= GameInfo.Projects.PROJECT_FIGHTER_KI100_II.ID
PROJECT_N1K2			= GameInfo.Projects.PROJECT_FIGHTER_N1K2.ID
PROJECT_J2M				= GameInfo.Projects.PROJECT_FIGHTER_J2M.ID
PROJECT_G4M3			= GameInfo.Projects.PROJECT_BOMBER_G4M3.ID
PROJECT_I400			= GameInfo.Projects.PROJECT_SUBMARINE_I400.ID
PROJECT_YAMATO			= GameInfo.Projects.PROJECT_BATTLESHIP_YAMOTO.ID
PROJECT_SHOKAKU			= GameInfo.Projects.PROJECT_CARRIER_SHOKAKU.ID

-- Military Operation
OPERATION_WESERUBUNG		= GameInfo.Projects.OPERATION_WESERUBUNG.ID
OPERATION_SEELOWE			= GameInfo.Projects.OPERATION_SEELOWE.ID
OPERATION_CHINA				= GameInfo.Projects.OPERATION_CHINA.ID
OPERATION_PACIFIC			= GameInfo.Projects.OPERATION_PACIFIC.ID
OPERATION_FALLGELB			= GameInfo.Projects.OPERATION_FALLGELB.ID
OPERATION_SONNENBLUME		= GameInfo.Projects.OPERATION_SONNENBLUME.ID
OPERATION_TWENTYFIVE		= GameInfo.Projects.OPERATION_TWENTYFIVE.ID
OPERATION_MARITA			= GameInfo.Projects.OPERATION_MARITA.ID
OPERATION_TORCH				= GameInfo.Projects.OPERATION_TORCH.ID
OPERATION_MOTHERLANDCALL	= GameInfo.Projects.OPERATION_MOTHERLANDCALL.ID
OPERATION_URANUS			= GameInfo.Projects.OPERATION_URANUS.ID
OPERATION_MOSKWA			= GameInfo.Projects.OPERATION_MOSKWA.ID
OPERATION_HUSKY				= GameInfo.Projects.OPERATION_HUSKY.ID
OPERATION_AVALANCHE			= GameInfo.Projects.OPERATION_AVALANCHE.ID
OPERATION_OVERLORD			= GameInfo.Projects.OPERATION_OVERLORD.ID
OPERATION_FOURTEENTH_ARMY	= GameInfo.Projects.OPERATION_FOURTEENTH_ARMY.ID
OPERATION_TASK_FORCE_57		= GameInfo.Projects.OPERATION_TASK_FORCE_57.ID     
OPERATION_ALEUTIAN_ISLANDS	= GameInfo.Projects.OPERATION_ALEUTIAN_ISLANDS.ID
OPERATION_AUSTRALIA			= GameInfo.Projects.OPERATION_AUSTRALIA.ID
OPERATION_AUSTRALIAN_LIBERATION		= GameInfo.Projects.OPERATION_AUSTRALIAN_LIBERATION.ID
OPERATION_WATCHTOWER		= GameInfo.Projects.OPERATION_WATCHTOWER.ID
OPERATION_MARCH_BACK		= GameInfo.Projects.OPERATION_MARCH_BACK.ID
OPERATION_TAKE_DOWN			= GameInfo.Projects.OPERATION_TAKE_DOWN.ID

-- Available projects per nation
g_Major_Projects = {
	[FRANCE] = {		
		PROJECT_H39, PROJECT_R40, PROJECT_ARL_44,
		PROJECT_W15_TCC, PROJECT_AMR35_ZT3, PROJECT_37L,
		PROJECT_SAU40,
		PROJECT_HOTCHKISS,
		PROJECT_MB152, PROJECT_D520,
		PROJECT_LN401, PROJECT_BR690, },  --PROJECT_JOFFRE
	[USSR] = {
		PROJECT_BT7, PROJECT_T70, PROJECT_T34, PROJECT_T34_76, PROJECT_T34_85,
		PROJECT_KV1, PROJECT_KV2, PROJECT_IS_1, PROJECT_IS_2, PROJECT_IS_3, PROJECT_IS_7,
		PROJECT_SU122, PROJECT_SU152, PROJECT_ISU122, PROJECT_ISU152,
		PROJECT_ZIS30, PROJECT_SU76, PROJECT_SU85, PROJECT_SU100, 
		PROJECT_SU26, PROJECT_ZSU37, PROJECT_BM13, PROJECT_BM13_16,
		PROJECT_LAGG3, PROJECT_LA5, PROJECT_LA5_V2, PROJECT_LA7, PROJECT_YAK7, PROJECT_YAK9,
		PROJECT_IL2, PROJECT_IL2M3, PROJECT_IL10, PROJECT_IL4, PROJECT_TU2, PROJECT_PE8, PROJECT_SOYUZ,
		OPERATION_MOTHERLANDCALL, OPERATION_URANUS, OPERATION_MOSKWA}, 
	[GERMANY] = {
		PROJECT_PANZER_II_L, PROJECT_PANZER_III, PROJECT_PANZER_III_J, PROJECT_PANZER_IV, PROJECT_PANZER_IV_G, PROJECT_PANZER_IV_H,
		PROJECT_PANZER_V, PROJECT_PANZER_VI, PROJECT_PANZER_VIB, PROJECT_PANZER_VIII,
		PROJECT_MARDER_I, PROJECT_MARDER_II, PROJECT_MARDER_II_D, PROJECT_MARDER_III, PROJECT_MARDER_III_H, PROJECT_MARDER_III_M,
		PROJECT_HETZER, PROJECT_NASHORN, PROJECT_PZJ_IV, PROJECT_PZJ_IV_L70, PROJECT_JAGDPANTHER, PROJECT_FERDINAND, PROJECT_JAGDTIGER,
		PROJECT_STUG_III, PROJECT_STUG_III_F, PROJECT_STUG_III_G, PROJECT_STUG_IV, PROJECT_BRUMMBAR, PROJECT_STURMTIGER,
		PROJECT_FLK_PZI, PROJECT_FLK_PZ38, PROJECT_MOBELWAGEN, PROJECT_WIRBELWIND, PROJECT_OSTWIND, PROJECT_KUGELBLITZ, PROJECT_COELIAN,
		PROJECT_BISON, PROJECT_GRILLE, PROJECT_WESPE, PROJECT_HUMMEL,
		PROJECT_BF109F, PROJECT_BF109G, PROJECT_FW190, PROJECT_ME262, PROJECT_BF110F4, PROJECT_JU88C, PROJECT_HE219, 
		PROJECT_HE177, PROJECT_AR234, PROJECT_HO229, PROJECT_Z23, PROJECT_U_BOAT2, --PROJECT_ZEPPELIN,  
		OPERATION_WESERUBUNG, OPERATION_SEELOWE, OPERATION_FALLGELB, OPERATION_SONNENBLUME, OPERATION_TWENTYFIVE, OPERATION_MARITA},
	[ENGLAND] = {
		PROJECT_TETRARCH,  PROJECT_CRUISER_III, PROJECT_CRUISER_IV, PROJECT_A15, PROJECT_A15_MKIII, PROJECT_A13,
		PROJECT_MATILDAI, PROJECT_MATILDAII, PROJECT_VALENTINE,
		PROJECT_CAVALIER, PROJECT_CENTAUR, PROJECT_CROMWELL, PROJECT_CHALLENGER, PROJECT_COMET,
		PROJECT_M4_FIREFLY, PROJECT_CHURCHILL, PROJECT_CENTURION, PROJECT_TORTOISE,
		PROJECT_ACHILLES, PROJECT_ARCHER, PROJECT_CRUSADER, PROJECT_BISHOP, PROJECT_PRIEST, PROJECT_SEXTON,
		PROJECT_MOSQUITO, PROJECT_HURRICANE_II, PROJECT_SPITFIRE_V, PROJECT_SPITFIRE_IX, PROJECT_TYPHOON, PROJECT_TEMPEST, PROJECT_METEOR,
		PROJECT_BEAUFIGHTER, PROJECT_WHIRLWIND, PROJECT_LANCASTER, PROJECT_HALIFAX, PROJECT_U_CLASS, --PROJECT_ARK_ROYAL, PROJECT_ILLUSTRIOUS
		OPERATION_HUSKY, OPERATION_AVALANCHE, OPERATION_FOURTEENTH_ARMY, OPERATION_TASK_FORCE_57},
	[ITALY] = {
		PROJECT_M13_40, PROJECT_M14_41, PROJECT_M15_42,  PROJECT_P26_40, PROJECT_M11_39, PROJECT_L6_40,
		PROJECT_SM41, PROJECT_L40, PROJECT_M42M, PROJECT_M42T, PROJECT_43, PROJECT_AUTOCANNONE,
		PROJECT_G50, PROJECT_G55, PROJECT_MC202, PROJECT_MC205, PROJECT_CAPRONI,
		PROJECT_SM84, },   --PROJECT_AQUILA
	[GREECE] = {
		},
	[AMERICA] = {
		PROJECT_M3A1HT,
		PROJECT_M5STUART, PROJECT_M24CHAFFEE,
		PROJECT_M4SHERMAN, PROJECT_M4A1SHERMANIIA, PROJECT_SHERMAN_III, PROJECT_SHERMANIIIA, PROJECT_SHERMAN_IV, PROJECT_JUMBO, PROJECT_EASYEIGHT,
		PROJECT_M26, PROJECT_T28_95,
		PROJECT_M7, PROJECT_M12, PROJECT_M40,
		PROJECT_M10, PROJECT_M18, PROJECT_M36, PROJECT_M16A1,
		PROJECT_P51, PROJECT_P40, PROJECT_P38, PROJECT_F4F, PROJECT_F6F, PROJECT_F4U, PROJECT_P47,
		PROJECT_SB2C, PROJECT_TBF, PROJECT_A20, PROJECT_B25, PROJECT_B24, PROJECT_B29, 
		PROJECT_FLETCHER, PROJECT_IOWA, --PROJECT_ESSEX,
		OPERATION_TORCH, OPERATION_OVERLORD, OPERATION_AUSTRALIAN_LIBERATION, OPERATION_WATCHTOWER, OPERATION_MARCH_BACK, OPERATION_TAKE_DOWN},
	[JAPAN] = {
		PROJECT_TYPE97_SHINHOTO, PROJECT_TYPE1, PROJECT_TYPE3, PROJECT_TYPE4, PROJECT_TYPE4_CHITO, PROJECT_TYPE5, PROJECT_TYPE100,
		PROJECT_TYPE2, PROJECT_HO_NI_I, PROJECT_HO_NI_II, PROJECT_HO_NI_III, PROJECT_NA_TO, 
		PROJECT_HO_RO, PROJECT_HA_TO, PROJECT_TYPE98,
		PROJECT_A6M2, PROJECT_A6M5, PROJECT_A7M, PROJECT_KI43, PROJECT_KI44, PROJECT_KI84, PROJECT_KI61, PROJECT_KI100, PROJECT_KI100_II, 
		PROJECT_N1K2, PROJECT_J2M,
		PROJECT_G4M3, PROJECT_I400, PROJECT_YAMATO, --PROJECT_SHOKAKU,
		OPERATION_CHINA, OPERATION_PACIFIC, OPERATION_AUSTRALIA, OPERATION_ALEUTIAN_ISLANDS, },
}

-- Projects Table
g_ProjectsTable = { 
	-- Buildings : need one of building types listed
	-- Projects : need all projects type listed
	-- Scenarios : available in all scenario listed, refer to ScenarioName of modUserData.SetValue("RedLoading", "ScenarioName") in setup lua file
	-- triggering events for project availability : (if not set, project is immediatly available)
		-- Type define when the project is available
		-- TRIGGER_XP = another unit (set in Reference) must have gain this amount of XP during combat (XP from buildings are not counted)
		-- TRIGGER_DATE = when starting date is reached (yyyymmdd), each turn the project have ProbPerTur % of chance of being made available
	-- Repeat : project can be done again (example: for calling reinforcement)
	-- AIOnly : project can be produced only by the AI (It can be use for balance)

	---------------------------------------------------------------------
	-- France
	---------------------------------------------------------------------
	[PROJECT_H39] =  {
		Buildings = {ACADEMY, FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 100, Reference = FR_H35 },
		Repeat = false, -- just as an example, default is always false
	},
	[PROJECT_R40] =  {
		Buildings = {ACADEMY, FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 100, Reference = FR_R35 },
	},
	[PROJECT_ARL_44] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440101, ProbPerTurn = 15},
	},
	[PROJECT_W15_TCC] = {
		Buildings = {ACADEMY, FACTORY},
		Trigger = {Type = TRIGGER_DATE, Date = 19400101, ProbPerTurn = 20},
	},
	[PROJECT_AMR35_ZT3] = {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19390101, ProbPerTurn = 10},
	},
	[PROJECT_37L] = {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19400501, ProbPerTurn = 20},
	},
	[PROJECT_SAU40] = {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19400101, ProbPerTurn = 15},
	},
	[PROJECT_HOTCHKISS] = {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19390101, ProbPerTurn = 15},
	},
	[PROJECT_MB152] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19370701, ProbPerTurn = 25},
	},
	[PROJECT_D520] = {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19390101, ProbPerTurn = 15},
	},
	[PROJECT_LN401] = {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19390101, ProbPerTurn = 15},
	},
	[PROJECT_BR690] = {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19390101, ProbPerTurn = 15},
	},
	[PROJECT_JOFFRE] = {
		Buildings = {ACADEMY, SHIPYARD},
		Trigger = {Type = TRIGGER_DATE, Date = 19400601, ProbPerTurn = 10},
	},
	---------------------------------------------------------------------
	-- USSR
	---------------------------------------------------------------------
	[PROJECT_BT7] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19360101, ProbPerTurn = 15},
	},
	[PROJECT_T70] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19420101, ProbPerTurn = 15},
	},
	[PROJECT_T34] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19400601, ProbPerTurn = 15},
	},
	[PROJECT_T34_76] =  {
		Buildings = {ACADEMY, LAND_FACTORY},	
		Trigger = {Type = TRIGGER_XP, XP = 250, Reference = RU_T34},
	},
	[PROJECT_T34_85] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_XP, XP = 500, Reference = RU_T34_76},
	},
	[PROJECT_KV1] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19390101, ProbPerTurn = 10},
	},
	[PROJECT_KV2] =  {
		Buildings = {ACADEMY, LAND_FACTORY},	
		Projects = {PROJECT_KV1},	-- available immediatly after KV-1 project is done
	},
	[PROJECT_IS_1] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420901, ProbPerTurn = 20},
	},
	[PROJECT_IS_2] =  {
		Buildings = {ACADEMY},	
		Projects = {PROJECT_IS_1},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430601, ProbPerTurn = 20},
	},
	[PROJECT_IS_3] =  {
		Buildings = {ACADEMY},		
		Trigger = {Type = TRIGGER_DATE, Date = 19451201, ProbPerTurn = 20},
	},
	[PROJECT_IS_7] =  {
		Buildings = {ACADEMY},		
		Trigger = {Type = TRIGGER_DATE, Date = 19480101, ProbPerTurn = 20},
	},
	[PROJECT_SU26] =  {
		Buildings = {ACADEMY},		
		Trigger = {Type = TRIGGER_DATE, Date = 19410401, ProbPerTurn = 20},
	},
	[PROJECT_ZSU37] =  {
		Buildings = {ACADEMY},		
		Trigger = {Type = TRIGGER_DATE, Date = 19440101, ProbPerTurn = 20},
	},
	[PROJECT_BM13] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19390801, ProbPerTurn = 20},
	},
	[PROJECT_BM13_16] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_XP, XP = 150, Reference = RU_BM13},
	},
	[PROJECT_SU122] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19421001, ProbPerTurn = 20},
	},
	[PROJECT_SU152] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_SU122},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430101, ProbPerTurn = 20},
	},
	[PROJECT_ISU122] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19431001, ProbPerTurn = 20},
	},
	[PROJECT_ISU152] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_ISU122},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440201, ProbPerTurn = 20},
	},
	[PROJECT_ZIS30] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19410701, ProbPerTurn = 20},
	},
	[PROJECT_SU76] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19421101, ProbPerTurn = 20},
	},
	[PROJECT_SU85] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_SU76},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430601, ProbPerTurn = 20},
	},
	[PROJECT_SU100] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_SU85},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440701, ProbPerTurn = 20},
	},
	[PROJECT_LAGG3] =  {
		Buildings = {ACADEMY},		
		Trigger = {Type = TRIGGER_DATE, Date = 19401101, ProbPerTurn = 35},
	},	
	[PROJECT_LA5] =  {
		Buildings = {ACADEMY, SMALL_AIR_FACTORY},	
		Trigger = {Type = TRIGGER_XP, XP = 150, Reference = RU_LAGG3},
	},		
	[PROJECT_LA5_V2] =  {
		Buildings = {ACADEMY, SMALL_AIR_FACTORY},	
		Trigger = {Type = TRIGGER_XP, XP = 300, Reference = RU_LA5},
	},
	[PROJECT_LA7] =  {
		Buildings = {ACADEMY, SMALL_AIR_FACTORY},	
		Trigger = {Type = TRIGGER_XP, XP = 500, Reference = RU_LA5_V2},
	},	
	[PROJECT_YAK7] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19410901, ProbPerTurn = 35},
	},
	[PROJECT_YAK9] =  {
		Buildings = {ACADEMY},	
		Projects = {PROJECT_YAK7},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420801, ProbPerTurn = 35},
	},
	[PROJECT_IL2] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19401101, ProbPerTurn = 15},
	},
	[PROJECT_IL2M3] =  {
		Buildings = {ACADEMY, SMALL_AIR_FACTORY},	
		Trigger = {Type = TRIGGER_XP, XP = 200, Reference = RU_IL2},
	},
	[PROJECT_IL10] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19440401, ProbPerTurn = 15},
	},
	[PROJECT_PE8] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19390101, ProbPerTurn = 3},
	},
	[PROJECT_TU2] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19410101, ProbPerTurn = 10},
	},
	[PROJECT_IL4] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19400101, ProbPerTurn = 8},
	},
	[PROJECT_SOYUZ] =  {
		Buildings = {ACADEMY},
	},
	---------------------------------------------------------------------
	-- Germany
	---------------------------------------------------------------------
	[PROJECT_PANZER_II_L] =  {
		Buildings = {ACADEMY, FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 300, Reference = GE_PANZER_II },
	},
	[PROJECT_PANZER_III] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19360701, ProbPerTurn = 100},
	},
	[PROJECT_PANZER_III_J] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 500, Reference = GE_PANZER_III },
	},
	[PROJECT_PANZER_IV] =  {
		Buildings = {ACADEMY},		
		Projects = {PROJECT_PANZER_III},	
		Trigger = {Type = TRIGGER_DATE, Date = 19370701, ProbPerTurn = 15},
	},
	[PROJECT_PANZER_IV_G] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 250, Reference = GE_PANZER_IV },
	},
	[PROJECT_PANZER_IV_H] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 750, Reference = GE_PANZER_IV_G },
	},
	[PROJECT_PANZER_V] =  {
		Buildings = {ACADEMY},	
		Projects = {PROJECT_PANZER_IV},
		Trigger = {Type = TRIGGER_DATE, Date = 19420901, ProbPerTurn = 15},
	},
	[PROJECT_PANZER_VI] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420301, ProbPerTurn = 20},
	},
	[PROJECT_PANZER_VIB] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_PANZER_VI},
		Trigger = {Type = TRIGGER_DATE, Date = 19431101, ProbPerTurn = 20},
	},
	[PROJECT_PANZER_VIII] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440501, ProbPerTurn = 10},
	},
	[PROJECT_STUG_III] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19400101, ProbPerTurn = 15},
	},
	[PROJECT_STUG_III_F] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 100, Reference = GE_STUG_III },
	},
	[PROJECT_STUG_III_G] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 250, Reference = GE_STUG_III_F },
	},
	[PROJECT_STUG_IV] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_STUG_III},	
		Trigger = {Type = TRIGGER_DATE, Date = 19411001, ProbPerTurn = 15},
	},
	[PROJECT_BRUMMBAR] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_STUG_IV},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430101, ProbPerTurn = 15},
	},
	[PROJECT_STURMTIGER] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_BRUMMBAR},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440601, ProbPerTurn = 15},
	},	
	[PROJECT_MARDER_II] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19411201, ProbPerTurn = 15},
	},
	[PROJECT_MARDER_II_D] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 250, Reference = GE_MARDER_II },
	},
	[PROJECT_MARDER_III] =  {
		Buildings = {ACADEMY},	
		Projects = {PROJECT_MARDER_II},
		Trigger = {Type = TRIGGER_DATE, Date = 19420901, ProbPerTurn = 15},
	},
	[PROJECT_MARDER_III_H] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 100, Reference = GE_MARDER_III },
	},
	[PROJECT_MARDER_III_M] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 250, Reference = GE_MARDER_III_H },
	},
	[PROJECT_HETZER] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440101, ProbPerTurn = 15},
	},
	[PROJECT_NASHORN] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420201, ProbPerTurn = 15},
	},
	[PROJECT_PZJ_IV] =  {
		Buildings = {ACADEMY},	
		Projects = {PROJECT_NASHORN},
		Trigger = {Type = TRIGGER_DATE, Date = 19430201, ProbPerTurn = 15},
	},
	[PROJECT_PZJ_IV_L70] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 100, Reference = GE_PZJ_IV },
	},
	[PROJECT_JAGDPANTHER] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_PZJ_IV},	
		Trigger = {Type = TRIGGER_DATE, Date = 19431101, ProbPerTurn = 15},
	},
	[PROJECT_FERDINAND] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420901, ProbPerTurn = 15},
	},
	[PROJECT_JAGDTIGER] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_FERDINAND},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440701, ProbPerTurn = 15},
	},
	[PROJECT_FLK_PZI] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19390101, ProbPerTurn = 25},
	},
	[PROJECT_FLK_PZ38] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_DATE, Date = 19411001, ProbPerTurn = 15},
	},
	[PROJECT_MOBELWAGEN] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430801, ProbPerTurn = 15},
	},
	[PROJECT_WIRBELWIND] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 75, Reference = GE_MOBILE_AA_MOBEL },
	},
	[PROJECT_OSTWIND] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 100, Reference = GE_MOBILE_AA_WIRBEL },
	},
	[PROJECT_KUGELBLITZ] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 125, Reference = GE_MOBILE_AA_OST },
	},
	[PROJECT_COELIAN] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_MOBELWAGEN},
		Trigger = {Type = TRIGGER_DATE, Date = 19450101, ProbPerTurn = 15},
	},
	[PROJECT_BISON] =  {
		Buildings = {ACADEMY},		
		Trigger = {Type = TRIGGER_DATE, Date = 19400101, ProbPerTurn = 15},
	},
	[PROJECT_GRILLE] =  {
		Buildings = {ACADEMY},	
		Projects = {PROJECT_BISON},
		Trigger = {Type = TRIGGER_DATE, Date = 19411201, ProbPerTurn = 15},
	},
	[PROJECT_WESPE] =  {
		Buildings = {ACADEMY},	
		Projects = {PROJECT_GRILLE},
		Trigger = {Type = TRIGGER_DATE, Date = 19421201, ProbPerTurn = 15},
	},
	[PROJECT_HUMMEL] =  {
		Buildings = {ACADEMY},	
		Projects = {PROJECT_WESPE},
		Trigger = {Type = TRIGGER_DATE, Date = 19440201, ProbPerTurn = 15},
	},
	[PROJECT_BF109F] =  {
		Buildings = {ACADEMY, SMALL_AIR_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 250, Reference = GE_BF109 },
	},
	[PROJECT_BF109G] =  {
		Buildings = {ACADEMY, SMALL_AIR_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 750, Reference = GE_BF109_F },
	},
	[PROJECT_BF110F4] =  {
		Buildings = {ACADEMY, MEDIUM_AIR_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 250, Reference = GE_BF110 },
	},
	[PROJECT_FW190] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19410501, ProbPerTurn = 20},
	},
	[PROJECT_ME262] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19440401, ProbPerTurn = 20},
	},
	[PROJECT_JU88C] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19400101, ProbPerTurn = 15},
	},
	[PROJECT_HE219] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19430501, ProbPerTurn = 10},
	},
	[PROJECT_HE177] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19410601, ProbPerTurn = 10},
	},
	[PROJECT_AR234] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19440701, ProbPerTurn = 10},
	},
	[PROJECT_HO229] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19450601, ProbPerTurn = 10},
	},
	[PROJECT_ZEPPELIN] = {
		Buildings = {ACADEMY, SHIPYARD},
		Trigger = {Type = TRIGGER_DATE, Date = 19400601, ProbPerTurn = 10},
	},
	[PROJECT_Z23] = {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19380701, ProbPerTurn = 25},
	},
	[PROJECT_U_BOAT2] = {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19410601, ProbPerTurn = 25},
	},
	---------------------------------------------------------------------
	-- U.K.
	---------------------------------------------------------------------	
	[PROJECT_TETRARCH] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19380101, ProbPerTurn = 25},
	},	
	[PROJECT_MATILDAI] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19360701, ProbPerTurn = 15},
	},
	[PROJECT_MATILDAII] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19370101, ProbPerTurn = 10},
	},
	[PROJECT_VALENTINE] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19390210, ProbPerTurn = 35},
	},
	[PROJECT_CRUISER_II] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19370601, ProbPerTurn = 20},
	},
	[PROJECT_CRUISER_III] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19380301, ProbPerTurn = 20},
	},
	[PROJECT_CRUISER_IV] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_DATE, Date = 19390101, ProbPerTurn = 20},
	},
	[PROJECT_A13] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_CRUISER_III},	
		Trigger = {Type = TRIGGER_DATE, Date = 19390601, ProbPerTurn = 20},
	},
	[PROJECT_A15] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_A13},	
		Trigger = {Type = TRIGGER_DATE, Date = 19400601, ProbPerTurn = 35},
	},
	[PROJECT_A15_MKIII] =  {
		Buildings = {ACADEMY, LAND_FACTORY},	
		Trigger = {Type = TRIGGER_XP, XP = 75, Reference = UK_A15_CRUSADER},
	},
	[PROJECT_CAVALIER] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19420101, ProbPerTurn = 15},
	},
	[PROJECT_CENTAUR] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 75, Reference = UK_A24 },
	},
	[PROJECT_CROMWELL] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 150, Reference = UK_A27 },
	},
	[PROJECT_CHALLENGER] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_CAVALIER},
		Trigger = {Type = TRIGGER_DATE, Date = 19430601, ProbPerTurn = 15},
	},
	[PROJECT_COMET] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_CHALLENGER},
		Trigger = {Type = TRIGGER_DATE, Date = 19440701, ProbPerTurn = 15},
	},
	[PROJECT_M3GRANT] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19390101, ProbPerTurn = 15},
	},
	[PROJECT_M4_FIREFLY] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19431201, ProbPerTurn = 15},
	},
	[PROJECT_CHURCHILL] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19410401, ProbPerTurn = 15},
	},
	[PROJECT_CENTURION] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19451001, ProbPerTurn = 15},
	},
	[PROJECT_TORTOISE] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19450701, ProbPerTurn = 15},
	},
	[PROJECT_ACHILLES] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420501, ProbPerTurn = 25},
	},
	[PROJECT_ARCHER] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19430101, ProbPerTurn = 15},
	},
	[PROJECT_CRUSADER] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19440201, ProbPerTurn = 15},
	},
	[PROJECT_BISHOP] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19410301, ProbPerTurn = 15},
	},
	[PROJECT_PRIEST] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420101, ProbPerTurn = 25},
	},
	[PROJECT_SEXTON] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430401, ProbPerTurn = 25},
	},
	[PROJECT_HURRICANE_II] =  {
		Buildings = {ACADEMY, SMALL_AIR_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 100, Reference = UK_HURRICANE },
	},
	[PROJECT_SPITFIRE_V] =  {
		Buildings = {ACADEMY, SMALL_AIR_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 250, Reference = UK_SPITFIRE },
	},
	[PROJECT_SPITFIRE_IX] =  {
		Buildings = {ACADEMY, SMALL_AIR_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 750, Reference = UK_SPITFIRE_V },
	},
	[PROJECT_TYPHOON] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19401201, ProbPerTurn = 15},
	},
	[PROJECT_TEMPEST] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19431101, ProbPerTurn = 15},
	},
	[PROJECT_METEOR] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19440401, ProbPerTurn = 15},
	},
	[PROJECT_WHIRLWIND] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19391001, ProbPerTurn = 15},
	},
	[PROJECT_BEAUFIGHTER] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19410601, ProbPerTurn = 10},
	},
	[PROJECT_MOSQUITO] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19410101, ProbPerTurn = 10},
	},
	[PROJECT_LANCASTER] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420101, ProbPerTurn = 25},
	},
	[PROJECT_HALIFAX] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19411001, ProbPerTurn = 25},
	},
	[PROJECT_ARK_ROYAL] = {
		Buildings = {ACADEMY, SHIPYARD},
		Trigger = {Type = TRIGGER_DATE, Date = 19400601, ProbPerTurn = 10},
	},
	[PROJECT_ILLUSTRIOUS] = {
		Buildings = {ACADEMY, SHIPYARD},
		Trigger = {Type = TRIGGER_DATE, Date = 19411101, ProbPerTurn = 10},
	},
	[PROJECT_U_CLASS] = {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19400701, ProbPerTurn = 100},
	},
	---------------------------------------------------------------------
	-- Italy
	---------------------------------------------------------------------
	[PROJECT_L6_40] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19390101, ProbPerTurn = 25},
	},
	[PROJECT_M11_39] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19390101, ProbPerTurn = 25},
	},
	[PROJECT_M13_40] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19391201, ProbPerTurn = 10},
	},
	[PROJECT_M14_41] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 350, Reference = IT_M13_40 },
	},
	[PROJECT_M15_42] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 700, Reference = IT_M14_41 },
	},
	[PROJECT_P26_40] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19430401, ProbPerTurn = 10},
	},
	[PROJECT_SM41] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19410901, ProbPerTurn = 25},
	},
	[PROJECT_L40] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19400701, ProbPerTurn = 25},
	},
	[PROJECT_M41] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19410701, ProbPerTurn = 25},
	},
	[PROJECT_M42M] =  {
		Buildings = {ACADEMY},	
		Projects = {PROJECT_M41},
		Trigger = {Type = TRIGGER_DATE, Date = 19420401, ProbPerTurn = 25},
	},
	[PROJECT_M42T] =  {
		Buildings = {ACADEMY, LAND_FACTORY},
		Trigger = {Type = TRIGGER_XP, XP = 150, Reference = IT_M42M },
	},
	[PROJECT_M43] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_M42M},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430501, ProbPerTurn = 25},
	},
	[PROJECT_AUTOCANNONE] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19391201, ProbPerTurn = 25},
	},
	[PROJECT_G50] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19370201, ProbPerTurn = 25},
	},
	[PROJECT_G55] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430301, ProbPerTurn = 15},
	},
	[PROJECT_MC202] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19410401, ProbPerTurn = 25},
	},
	[PROJECT_MC205] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_MC202},	
		Trigger = {Type = TRIGGER_DATE, Date = 19421201, ProbPerTurn = 25},
	},
	[PROJECT_CAPRONI] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19440801, ProbPerTurn = 15},
	},
	[PROJECT_SM84] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19400601, ProbPerTurn = 15},
	},
	[PROJECT_AQUILA] = {
		Buildings = {ACADEMY, SHIPYARD},
		Trigger = {Type = TRIGGER_DATE, Date = 19400601, ProbPerTurn = 10},
	},
	---------------------------------------------------------------------
	-- USA
	---------------------------------------------------------------------	
	[PROJECT_M3A1HT] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19410501, ProbPerTurn = 15},
	},
	[PROJECT_M5STUART] =  {
		Buildings = {ACADEMY, FACTORY},
		Trigger = {Type = TRIGGER_DATE, Date = 19420401, ProbPerTurn = 15},
	},
	[PROJECT_M24CHAFFEE] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_M5STUART},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430301, ProbPerTurn = 15},
	},
	[PROJECT_M4SHERMAN] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19400801, ProbPerTurn = 15},
	},
	[PROJECT_M4A1SHERMANIIA] =  {
		Buildings = {ACADEMY},	
		Projects = {PROJECT_M4SHERMAN},
		Trigger = {Type = TRIGGER_DATE, Date = 19420901, ProbPerTurn = 20},
	},
	[PROJECT_SHERMAN_III] =  {
		Buildings = {ACADEMY},	
		Projects = {PROJECT_M4A1SHERMANIIA},
		Trigger = {Type = TRIGGER_DATE, Date = 19430301, ProbPerTurn = 20},
	},
	[PROJECT_SHERMANIIIA] =  {
		Buildings = {ACADEMY, LAND_FACTORY},	
		Projects = {PROJECT_SHERMAN_III},
		Trigger = {Type = TRIGGER_DATE, Date = 19430901, ProbPerTurn = 20},
	},
	[PROJECT_SHERMAN_IV] =  {
		Buildings = {ACADEMY},
		Projects = {PROJECT_SHERMANIII},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440101, ProbPerTurn = 50},
	},
	[PROJECT_JUMBO] =  {
		Buildings = {ACADEMY, LAND_FACTORY},	
		Trigger = {Type = TRIGGER_XP, XP = 75, Reference = US_SHERMAN_IV},
	},
	[PROJECT_EASYEIGHT] =  {
		Buildings = {ACADEMY, LAND_FACTORY},	
		Trigger = {Type = TRIGGER_XP, XP = 100, Reference = US_SHERMAN_JUMBO},
	},
	[PROJECT_M26] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440601, ProbPerTurn = 25},
	},
	[PROJECT_T28_95] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19450401, ProbPerTurn = 25},
	},
	[PROJECT_M10] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420401, ProbPerTurn = 25},
	},
	[PROJECT_M18] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430601, ProbPerTurn = 25},
	},
	[PROJECT_M36] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440401, ProbPerTurn = 25},
	},
	[PROJECT_M7] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420101, ProbPerTurn = 25},
	},
	[PROJECT_M12] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430101, ProbPerTurn = 25},
	},
	[PROJECT_M40] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440101, ProbPerTurn = 25},
	},
	[PROJECT_M16A1] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430501, ProbPerTurn = 25},
	},
	[PROJECT_P47] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420301, ProbPerTurn = 25},
	},
	[PROJECT_P40] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19380601, ProbPerTurn = 10},
	},
	[PROJECT_P38] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19390101, ProbPerTurn = 20},
	},
	[PROJECT_P51] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430101, ProbPerTurn = 15},
	},
	[PROJECT_F4F] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19400101, ProbPerTurn = 15},
	},
	[PROJECT_F6F] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19421101, ProbPerTurn = 15},
	},
	[PROJECT_F4U] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420401, ProbPerTurn = 15},
	},
	[PROJECT_SB2C] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19421201, ProbPerTurn = 15},
	},
	[PROJECT_TBF] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19410801, ProbPerTurn = 15},
	},
	[PROJECT_A20] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19401120, ProbPerTurn = 50},
	},
	[PROJECT_B24] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19401220, ProbPerTurn = 50},
	},
	[PROJECT_B25] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19400701, ProbPerTurn = 20},
	},
	[PROJECT_B29] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440220, ProbPerTurn = 50},
	},
	[PROJECT_FLETCHER] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19420201, ProbPerTurn = 25},
	},
	[PROJECT_IOWA] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19420601, ProbPerTurn = 25},
	},
	[PROJECT_ESSEX] = {
		Buildings = {ACADEMY, SHIPYARD},
		Trigger = {Type = TRIGGER_DATE, Date = 19430401, ProbPerTurn = 50},
	},
	---------------------------------------------------------------------
	-- Japan
	---------------------------------------------------------------------
	[PROJECT_TYPE97_SHINHOTO] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19410101, ProbPerTurn = 15},
	},
	[PROJECT_TYPE1] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19410601, ProbPerTurn = 15},
	},
	[PROJECT_TYPE3] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440101, ProbPerTurn = 15},
	},
	[PROJECT_TYPE4] =  {
		Buildings = {FACTORY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440101, ProbPerTurn = 35},
	},
	[PROJECT_TYPE4_CHITO] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420601, ProbPerTurn = 10},
	},
	[PROJECT_TYPE5] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430301, ProbPerTurn = 10},
	},
	[PROJECT_TYPE100] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19450201, ProbPerTurn = 10},
	},
	[PROJECT_TYPE2] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420301, ProbPerTurn = 10},
	},
	[PROJECT_HO_RO] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19431201, ProbPerTurn = 10},
	},
	[PROJECT_HA_TO] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440601, ProbPerTurn = 10},
	},
	[PROJECT_HO_NI_I] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19410501, ProbPerTurn = 10},
	},
	[PROJECT_HO_NI_II] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_XP, XP = 150, Reference = JP_HO_NI_I},
	},
	[PROJECT_HO_NI_III] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_XP, XP = 350, Reference = JP_HO_NI_II},
	},
	[PROJECT_NA_TO] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19450301, ProbPerTurn = 10},
	},
	[PROJECT_TYPE98] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420101, ProbPerTurn = 10},
	},
	[PROJECT_A6M2] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19400401, ProbPerTurn = 25},
	},	
	[PROJECT_A6M5] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_XP, XP = 250, Reference = JP_A6M2},
	},
	[PROJECT_A7M] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19440101, ProbPerTurn = 10},
	},
	[PROJECT_KI43] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19401201, ProbPerTurn = 10},
	},
	[PROJECT_KI44] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_XP, XP = 250, Reference = JP_KI43},
	},
	[PROJECT_KI84] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_XP, XP = 750, Reference = JP_KI44},
	},
	[PROJECT_KI61] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19430101, ProbPerTurn = 10},
	},
	[PROJECT_KI100] =  {
		Buildings = {ACADEMY},
		Trigger = {Type = TRIGGER_DATE, Date = 19440601, ProbPerTurn = 10},
	},
	[PROJECT_KI100_II] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_XP, XP = 250, Reference = JP_KI100},
	},
	[PROJECT_N1K2] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19431201, ProbPerTurn = 10},
	},
	[PROJECT_J2M] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19431001, ProbPerTurn = 10},
	},
	[PROJECT_G4M3] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19410401, ProbPerTurn = 10},
	},
	[PROJECT_I400] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19400201, ProbPerTurn = 25},
	},
	[PROJECT_YAMATO] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19410701, ProbPerTurn = 25},
	},
	[PROJECT_SHOKAKU] =  {
		Buildings = {ACADEMY},	
		Trigger = {Type = TRIGGER_DATE, Date = 19390101, ProbPerTurn = 25},
	},
	---------------------------------------------------------------------
	-- MILITARY OPERATIONS	
	---------------------------------------------------------------------
	[OPERATION_WESERUBUNG] =  {
		Buildings = {BASE},	
		Scenarios = {"Earth1936", "Euro1940", "AmericaEuro1936"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19400101, ProbPerTurn = 100},
		TopSecret = false,
	},

	[OPERATION_SEELOWE] =  {
		Buildings = {BASE},	
		Scenarios = {"Earth1936", "Euro1940", "AmericaEuro1936" },	
		Trigger = {Type = TRIGGER_DATE, Date = 19400401, ProbPerTurn = 100},
		AIOnly = false,
		TopSecret = false,
	},	
	
	[OPERATION_CHINA] =  {
		Buildings = {BASE},	
		Scenarios = {"Earth1936", },	
		Trigger = {Type = TRIGGER_DATE, Date = 19370701, ProbPerTurn = 100},
		TopSecret = false,
	},
	[OPERATION_PACIFIC] =  {
		Buildings = {BASE},	
		Scenarios = {"Earth1936", },	
		Trigger = {Type = TRIGGER_DATE, Date = 19411201, ProbPerTurn = 100},
		TopSecret = false,
	},
	[OPERATION_MARITA] =  {
		Buildings = {BASE},	
		Scenarios = {"Earth1936", "AmericaEuro1936"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19410101, ProbPerTurn = 100},
		AIOnly = false,
		TopSecret = false,
	},
	[OPERATION_TWENTYFIVE] =  {
		Buildings = {BASE},	
		Scenarios = {"Earth1936", "Euro1940","AmericaEuro1936"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19410101, ProbPerTurn = 100},
		AIOnly = false,
		TopSecret = false,
	},
	[OPERATION_SONNENBLUME] =  {
		Buildings = {BASE},	
		Scenarios = {"Earth1936", "Euro1940", "AmericaEuro1936" },	
		Trigger = {Type = TRIGGER_DATE, Date = 19410602, ProbPerTurn = 100},
		Repeat = true,
		TopSecret = false,
	},
	[OPERATION_TORCH] =  {
		Buildings = {BASE},	
		Scenarios = {"Earth1936", "Euro1940", "AmericaEuro1936"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420601, ProbPerTurn = 100},
		TopSecret = false,
	},	
	[OPERATION_MOTHERLANDCALL] =  {
		Buildings = {RADIO},	
		Scenarios = {"Earth1936", "Euro1940", "AmericaEuro1936"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19411204, ProbPerTurn = 100},
		Projects = {PROJECT_T34},
		Repeat = true,
		TopSecret = false,
	},	
	[OPERATION_URANUS] =  {
		Buildings = {BASE},	
		Scenarios = {"Earth1936", "Euro1940", "AmericaEuro1936"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420301, ProbPerTurn = 100},
		TopSecret = false,
	},	
	[OPERATION_FALLGELB] =  {
		Buildings = {BASE},	
		Scenarios = {"Earth1936", "Euro1940", "AmericaEuro1936"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19391101, ProbPerTurn = 100},
		AIOnly = false,
		TopSecret = false,
	},	
	[OPERATION_HUSKY] =  {
		Buildings = {BASE},	
		Scenarios = {"Earth1936", "Euro1940", "AmericaEuro1936"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430201, ProbPerTurn = 100},
		TopSecret = false,
	},	
	[OPERATION_AVALANCHE] =  {
		Buildings = {BASE},	
		Scenarios = {"Earth1936", "Euro1940", "AmericaEuro1936"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430501, ProbPerTurn = 100},
		TopSecret = false,
	},
	[OPERATION_FOURTEENTH_ARMY] =  {
		Buildings = {BASE},	
		Scenarios = {"Pacific1942"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430201, ProbPerTurn = 100}, 
	},
	[OPERATION_TASK_FORCE_57] =  {
		Buildings = {BASE},	
		Scenarios = {"Pacific1942"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440510, ProbPerTurn = 100},
	},
	[OPERATION_ALEUTIAN_ISLANDS] =  {
		Buildings = {BASE},	
		Scenarios = {"Pacific1942"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420210, ProbPerTurn = 100}, 
		AIOnly = false,
		TopSecret = false,
	},
	[OPERATION_AUSTRALIA] =  {
		Buildings = {BASE},	
		Scenarios = {"Pacific1942"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420110, ProbPerTurn = 100},
		AIOnly = false,
		TopSecret = false,
	},
	[OPERATION_AUSTRALIAN_LIBERATION] =  {
		Buildings = {BASE},	
		Scenarios = {"Pacific1942"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440201, ProbPerTurn = 100},
		AIOnly = false,
		TopSecret = false,
	},
	[OPERATION_WATCHTOWER] =  {
		Buildings = {BASE},	
		Scenarios = {"Pacific1942"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19420501, ProbPerTurn = 100},
		AIOnly = false,
		TopSecret = false,
	},
	[OPERATION_MARCH_BACK] =  {
		Buildings = {BASE},	
		Scenarios = {"Pacific1942"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19430601, ProbPerTurn = 100},
		AIOnly = false,
		TopSecret = false,
	},
	[OPERATION_TAKE_DOWN] =  {
		Buildings = {BASE},	
		Scenarios = {"Pacific1942"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440801, ProbPerTurn = 100},
		AIOnly = false,
		TopSecret = false,
	},
	[OPERATION_OVERLORD] =  {
		Buildings = {BASE},	
		Scenarios = {"Earth1936", "Euro1940", "AmericaEuro1936"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440101, ProbPerTurn = 100},
		TopSecret = false,
	},	
	[OPERATION_MOSKWA] =  {
		Buildings = {BASE},	
		Scenarios = {"Earth1936", "Euro1940", "AmericaEuro1936"},	
		Trigger = {Type = TRIGGER_DATE, Date = 19440101, ProbPerTurn = 100},
		TopSecret = false,
	},				
}

-- Units needing a project done before being build...
g_UnitsProject = {
	-- Mechanized Infantry	
	[FR_MECH_INFANTRY] = PROJECT_M3A1HT,
	[US_MECH_INFANTRY] = PROJECT_M3A1HT,
	[RU_MECH_INFANTRY] = PROJECT_M3A1HT,
	[UK_MECH_INFANTRY] = PROJECT_M3A1HT,
	-- Tanks
	[FR_R40] = PROJECT_R40,
	[FR_H39] = PROJECT_H39,
	[FR_ARL44] = PROJECT_ARL_44,
	[IT_L6_40] = PROJECT_L6_40,			
	[IT_M11_39] = PROJECT_M11_39,			
	[IT_M13_40] = PROJECT_M13_40,			
	[IT_M14_41] = PROJECT_M14_41,			
	[IT_M15_42] = PROJECT_M15_42,			
	[IT_P26_40] = PROJECT_P26_40,			
	[RU_BT7] = PROJECT_BT7,			
	[RU_T70] = PROJECT_T70,						
	[RU_T34] = PROJECT_T34,				
	[RU_T34_76] = PROJECT_T34_76,
	[RU_T34_85] = PROJECT_T34_85,
	[RU_KV1] = PROJECT_KV1,
	[RU_IS_1] = PROJECT_IS_1,
	[RU_IS_2] = PROJECT_IS_2,
	[RU_IS_3] = PROJECT_IS_3,
	[RU_IS_7] = PROJECT_IS_7,			
	[UK_CRUISER_III] = PROJECT_CRUISER_III,	
	[UK_CRUISER_IV] = PROJECT_CRUISER_IV,			
	[UK_TETRARCH] = PROJECT_TETRARCH,
	[UK_M3_GRANT] = PROJECT_M3GRANT,				
	[UK_MATILDA_I] = PROJECT_MATILDAI,			
	[UK_MATILDA_II] = PROJECT_MATILDAII,
	[UK_A10_VALENTINE] = PROJECT_VALENTINE,
	[UK_A13_COVENANTER] = PROJECT_A13,	
	[UK_A15_CRUSADER] = PROJECT_A15,
	[UK_A15_CRUSADER_MKIII] = PROJECT_A15_MKIII,
	[UK_A24] = PROJECT_CAVALIER,
	[UK_A27] = PROJECT_CENTAUR,
	[UK_CROMWELL] = PROJECT_CROMWELL,
	[UK_A30] = PROJECT_CHALLENGER,
	[UK_A34] = PROJECT_COMET,		
	[UK_M4_FIREFLY] = PROJECT_M4_FIREFLY,		
	[UK_CHURCHILL] = PROJECT_CHURCHILL,
	[UK_A41] = PROJECT_CENTURION,
	[UK_A39] = PROJECT_TORTOISE,		
	[GE_PANZER_II_L] = PROJECT_PANZER_II_L,		
	[GE_PANZER_III] = PROJECT_PANZER_III,		
	[GE_PANZER_III_J] = PROJECT_PANZER_III_J,		
	[GE_PANZER_IV] = PROJECT_PANZER_IV,		
	[GE_PANZER_IV_G] = PROJECT_PANZER_IV_G,		
	[GE_PANZER_IV_H] = PROJECT_PANZER_IV_H,
	[GE_PANZER_V] = PROJECT_PANZER_V,	
	[GE_PANZER_VI] = PROJECT_PANZER_VI,
	[GE_PANZER_VIB] = PROJECT_PANZER_VIB,
	[GE_PANZER_VIII] = PROJECT_PANZER_VIII,
	[US_M5STUART] = PROJECT_M5STUART,
	[US_M24CHAFFEE] = PROJECT_M24CHAFFEE,
	[US_SHERMAN] = PROJECT_M4SHERMAN,			
	[US_SHERMAN_IIA] = PROJECT_M4A1SHERMANIIA,			
	[US_SHERMAN_III] = PROJECT_SHERMAN_III,
	[US_SHERMAN_IIIA] = PROJECT_SHERMANIIIA,
	[US_SHERMAN_IV] = PROJECT_SHERMAN_IV,
	[US_SHERMAN_JUMBO] = PROJECT_JUMBO,
	[US_SHERMAN_EASYEIGHT] = PROJECT_EASYEIGHT,
	[US_M26_PERSHING] = PROJECT_M26,
	[US_T28_95] = PROJECT_T28_95,
	[JP_TYPE4] = PROJECT_TYPE4,		
	[JP_TYPE97_SHINHOTO]  = PROJECT_TYPE97_SHINHOTO,
	[JP_TYPE1] = PROJECT_TYPE1,			
	[JP_TYPE3] = PROJECT_TYPE3,			
	[JP_TYPE4_CHI_TO] = PROJECT_TYPE4_CHITO,		
	[JP_TYPE5] = PROJECT_TYPE5,	
	[JP_TYPE100] = PROJECT_TYPE100,	
	--Assault gun
	[FR_SAU40] = PROJECT_SAU40,
	[RU_SU122] = PROJECT_SU122,
	[RU_SU152] = PROJECT_SU152,
	[RU_KV2] = PROJECT_KV2,	
	[RU_ISU122] = PROJECT_ISU122,
	[RU_ISU152] = PROJECT_ISU152,	
	[GE_STUG_III] = PROJECT_STUG_III,
	[GE_STUG_III_F] = PROJECT_STUG_III_F,
	[GE_STUG_III_G] = PROJECT_STUG_III_G,
	[GE_STUG_IV] = PROJECT_STUG_IV,	
	[GE_BRUMMBAR] = PROJECT_BRUMMBAR,
	[GE_STURMTIGER] = PROJECT_STURMTIGER,
	[IT_SM41] = PROJECT_SM41,
	[JP_TYPE2] = PROJECT_TYPE2,
	--Tank destroyer
	[FR_W15_TCC] = PROJECT_W15_TCC,
	[FR_AMR35_ZT3] = PROJECT_AMR35_ZT3,
	[FR_37L] = PROJECT_37L,
	[GE_MARDER_II] = PROJECT_MARDER_II,
	[GE_MARDER_II_D] = PROJECT_MARDER_II_D,
	[GE_MARDER_III] = PROJECT_MARDER_III,
	[GE_MARDER_III_H] = PROJECT_MARDER_III_H,
	[GE_MARDER_III_M] = PROJECT_MARDER_III_M,
	[GE_HETZER] = PROJECT_HETZER,
	[GE_NASHORN] = PROJECT_NASHORN,
	[GE_PZJ_IV] = PROJECT_PZJ_IV,
	[GE_PZJ_IV_L70] = PROJECT_PZJ_IV_L70,
	[GE_JAGDPANTHER] = PROJECT_JAGDPANTHER,
	[GE_FERDINAND] = PROJECT_FERDINAND,
	[GE_JAGDTIGER] = PROJECT_JAGDTIGER,
	[UK_ARCHER] = PROJECT_ARCHER,
	[UK_ACHILLES] = PROJECT_ACHILLES,
	[RU_ZIS30] = PROJECT_ZIS30,
	[RU_SU76] = PROJECT_SU76,
	[RU_SU85] = PROJECT_SU85,
	[RU_SU100] = PROJECT_SU100,
	[IT_L40] = PROJECT_L40,
	[IT_M41] = PROJECT_M41,
	[IT_M42M] = PROJECT_M42M,
	[IT_M42T] = PROJECT_M42T,
	[IT_M43] = PROJECT_M43,
	[US_M10] = PROJECT_M10,
	[US_M18] = PROJECT_M18,
	[US_M36] = PROJECT_M36,
	[JP_HO_NI_I] = PROJECT_HO_NI_I,
	[JP_HO_NI_II] = PROJECT_HO_NI_II,
	[JP_HO_NI_III] = PROJECT_HO_NI_III,
	[JP_NA_TO] = PROJECT_NA_TO,
	-- Anti-aircraft	
	[FR_MOBILE_AA_GUN] = PROJECT_HOTCHKISS,
	[GE_MOBILE_AA_GUN] = PROJECT_FLK_PZI,
	[GE_MOBILE_AA_38] = PROJECT_FLK_PZ38,
	[GE_MOBILE_AA_MOBEL] = PROJECT_MOBELWAGEN,
	[GE_MOBILE_AA_WIRBEL] = PROJECT_WIRBELWIND,
	[GE_MOBILE_AA_OST] = PROJECT_OSTWIND,
	[GE_MOBILE_AA_KUGEL] = PROJECT_KUGELBLITZ,
	[GE_MOBILE_AA_COELIAN] = PROJECT_COELIAN,
	[RU_ZSU37] = PROJECT_ZSU37,
	[UK_MOBILE_AA_GUN] = PROJECT_CRUSADER,
	[IT_AUTOCANNONE] = PROJECT_AUTOCANNONE,
	[US_M16A1] = PROJECT_M16A1,
	[JP_TYPE98] = PROJECT_TYPE98,
	-- SPG	
	[RU_SU26] = PROJECT_SU26,
	[RU_BM13] = PROJECT_BM13,
	[RU_BM13_16] = PROJECT_BM13_16,
	[GE_MOBILE_BISON] = PROJECT_BISON,
	[GE_MOBILE_GRILLE] = PROJECT_GRILLE,
	[GE_MOBILE_WESPE] = PROJECT_WESPE,
	[GE_MOBILE_HUMMEL] = PROJECT_HUMMEL,
	[UK_MOBILE_BISHOP] = PROJECT_BISHOP,
	[UK_PRIEST] = PROJECT_PRIEST,
	[UK_SEXTON] = PROJECT_SEXTON,
	[US_M7] = PROJECT_M7,
	[US_M12] = PROJECT_M12,
	[US_M40] = PROJECT_M40,
	[UK_SEXTON] = PROJECT_SEXTON,
	[JP_HO_RO] = PROJECT_HO_RO,
	[JP_HA_TO] = PROJECT_HA_TO,
	-- Fighters
	[FR_MB152] = PROJECT_MB152,
	[FR_D520] = PROJECT_D520,
	[FR_HURRICANE] = PROJECT_HURRICANE_II,
	[FR_P40] = PROJECT_P40,
	[FR_D790] = PROJECT_JOFFRE,
	[IT_G50] = PROJECT_G50,
	[IT_G55] = PROJECT_G55,
	[IT_C202] = PROJECT_MC202,
	[IT_C205] = PROJECT_MC205,
	[IT_CAPRONI] = PROJECT_CAPRONI,
	[RU_LAGG3] = PROJECT_LAGG3,
	[RU_LA5] = PROJECT_LA5,
	[RU_LA5_V2] = PROJECT_LA5_V2,
	[RU_LA7] = PROJECT_LA7,
	[RU_YAK_7] = PROJECT_YAK7,
	[RU_YAK_9] = PROJECT_YAK9,
	[UK_HURRICANE_II] = PROJECT_HURRICANE_II,
	[UK_SPITFIRE_V] = PROJECT_SPITFIRE_V,
	[UK_SPITFIRE_IX] = PROJECT_SPITFIRE_IX,
	[UK_TYPHOON] = PROJECT_TYPHOON,
	[UK_TEMPEST] = PROJECT_TEMPEST,
	[UK_METEOR] = PROJECT_METEOR,
	[GE_BF109_F] = PROJECT_BF109F,			
	[GE_BF109_G] = PROJECT_BF109G,		
	[GE_BF109_T] = PROJECT_ZEPPELIN,			
	[GE_FW190] = PROJECT_FW190,
	[GE_ME262] = PROJECT_ME262,
	[US_P40] = PROJECT_P40,	
	[US_P47] = PROJECT_P47,				
	[US_P51] = PROJECT_P51,
	[US_F6F] = PROJECT_F6F,
	[US_F4U] = PROJECT_F4U,	
	[JP_A6M2] = PROJECT_A6M2,
	[JP_A6M5] = PROJECT_A6M5,
	[JP_A7M] = PROJECT_A7M,
	[JP_KI43] = PROJECT_KI43,			
	[JP_KI44] = PROJECT_KI44,		
	[JP_KI84] = PROJECT_KI84,			
	[JP_KI61] = PROJECT_KI61,		
	[JP_KI100] = PROJECT_KI100,			
	[JP_KI100_II] = PROJECT_KI100_II,		
	[JP_N1K2] = PROJECT_N1K2,			
	[JP_J2M] = PROJECT_J2M,	
	[CH_P40N] = PROJECT_P40,	
	[GR_SPITFIRE] = PROJECT_SPITFIRE_V,

	-- Heavy Fighters			
	[UK_WHIRLWIND] = PROJECT_WHIRLWIND,
	[UK_BEAUFIGHTER] = PROJECT_BEAUFIGHTER,		
	[GE_BF110_F4] = PROJECT_BF110F4,			
	[GE_JU88_C] = PROJECT_JU88C,			
	[GE_HE219] = PROJECT_HE219,			
	[US_P38] = PROJECT_P38,			
	-- Attack Aircrafts
	[FR_LN401] = PROJECT_LN401,			
	[RU_IL2] = PROJECT_IL2,	
	[RU_IL2M3] = PROJECT_IL2M3,		
	[RU_IL10] = PROJECT_IL10,			
	[GE_JU87T] = PROJECT_ZEPPELIN,
	[US_SB2C] = PROJECT_SB2C,
	[US_TBF] = PROJECT_TBF,			
	-- Fast/Light Bombers
	[FR_BR690] = PROJECT_BR690,
	[FR_BR810] = PROJECT_JOFFRE,
	[GE_AR234] = PROJECT_AR234,
	[GE_HO229] = PROJECT_HO229,
	[UK_MOSQUITO] = PROJECT_MOSQUITO,			
	[RU_TU2] = PROJECT_TU2,	
	[US_A20] = PROJECT_A20,	
	[JP_G4M3] = PROJECT_G4M3,			
	-- Medium Bombers
	[IT_SM84] = PROJECT_SM84,		
	[RU_IL4] = PROJECT_IL4,
	[US_B25] = PROJECT_B25,				
	[CH_B25] = PROJECT_B25,
	-- Heavy Bombers				
	[RU_PE8] = PROJECT_PE8,				
	[GE_HE177] = PROJECT_HE177,			
	[UK_HALIFAX] = PROJECT_HALIFAX,
	[UK_LANCASTER] = PROJECT_LANCASTER,	
	[US_B24] = PROJECT_B24,
	[US_B29] = PROJECT_B29,
	-- Battleships
	[RU_BATTLESHIP] = PROJECT_SOYUZ,
	[US_BATTLESHIP_2] = PROJECT_IOWA,
	[JP_BATTLESHIP_2] = PROJECT_YAMATO,
	-- Carriers
	[FR_CARRIER] = PROJECT_JOFFRE,
	[GE_CARRIER] = PROJECT_ZEPPELIN,
	[UK_CARRIER] = PROJECT_ARK_ROYAL,
	[UK_CARRIER_2] = PROJECT_ILLUSTRIOUS,
	[IT_CARRIER] = PROJECT_AQUILA,
	[US_CARRIER_2] = PROJECT_ESSEX,
	[JP_CARRIER_2] = PROJECT_SHOKAKU,
	-- Destroyers
	[US_FLETCHER] = PROJECT_FLETCHER,
	[GE_DESTROYER_2] = PROJECT_Z23,
	-- Submarines
	[GE_SUBMARINE_2] = PROJECT_U_BOAT2,
	[UK_SUBMARINE_2] = PROJECT_U_CLASS,
	[JP_SUBMARINE_2] = PROJECT_I400,
}

-- Available projects per nation (Pedia)
g_Major_Operations = {
	[AMERICA]  = {OPERATION_TORCH, OPERATION_HUSKY, OPERATION_AVALANCHE, OPERATION_OVERLORD }, 
	[GERMANY]  = {OPERATION_WESERUBUNG, OPERATION_SEELOWE, OPERATION_FALLGELB, OPERATION_SONNENBLUME, OPERATION_TWENTYFIVE, OPERATION_MARITA}, 
	[ENGLAND]  = {OPERATION_HUSKY, OPERATION_AVALANCHE, OPERATION_FOURTEENTH_ARMY, OPERATION_TASK_FORCE_57}, 
	[USSR] 	   = {OPERATION_MOTHERLANDCALL, OPERATION_URANUS}, 
	[JAPAN]    = {OPERATION_CHINA, OPERATION_PACIFIC, OPERATION_ALEUTIAN_ISLANDS, OPERATION_AUSTRALIA}, 
}
	

